name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - 'fitpulse/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fitpulse

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44'
          channel: 'stable'

      - run: flutter pub get

      - run: flutter build web --release

      - run: npx firebase-tools deploy --only hosting --project fitpu1se --token "${{ secrets.FIREBASE_TOKEN }}"
